name: Build Claws Mail Bundled Binary for Void

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # Ubuntu 24.04, glibc-based

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build tools and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential curl tar pkg-config \
            git wget \
            libetpan-dev libgnutls28-dev \
            libarchive-dev \
            ghostscript spamassassin \
            libfuse-dev libgpgme-dev libenchant-2-dev \
            libldap2-dev libdb-dev libx11-dev libsm-dev \
            libgumbo-dev libsecret-1-dev \
            libperl-dev python3-dev libical-dev \
            libgtk-3-dev libcanberra-dev libnotify-dev \
            libjson-glib-dev libglib2.0-dev \
            libwebkit2gtk-4.0-dev qtbase5-dev \
            libpoppler-glib-dev libsoup2.4-dev

      - name: Install ICU 74 from source
        run: |
          wget https://github.com/unicode-org/icu/releases/download/release-74-2/icu4c-74_2-src.tgz -O icu.tar.gz
          tar -xzf icu.tar.gz
          cd icu/source
          ./configure --prefix=/usr --disable-static
          make -j$(nproc)
          sudo make install
          rm -rf ../../icu.tar.gz ../../icu
          ls -l /usr/lib/libicu*.so.74 || { echo "ICU 74 libraries not found"; exit 1; }
          export LD_LIBRARY_PATH=/usr/lib:/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
          echo "LD_LIBRARY_PATH=/usr/lib:/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH" >> $GITHUB_ENV

      - name: Download Claws Mail source
        run: |
          mkdir -p ~/claws-mail-build
          cd ~/claws-mail-build
          wget "https://www.claws-mail.org/download.php?file=releases/claws-mail-4.3.0.tar.xz" -O claws-mail-4.3.0.tar.xz
          tar -xf claws-mail-4.3.0.tar.xz

      - name: Configure Claws Mail with all plugins
        run: |
          cd ~/claws-mail-build/claws-mail-4.3.0
          ./configure \
            --prefix=/usr \
            --enable-gtk3 --enable-libetpan --enable-gnutls --enable-pgp-core \
            --enable-pgp-inline --enable-pgp-mime --enable-enchant --enable-poppler \
            --enable-canberra --enable-notify --enable-perl --enable-python \
            --enable-vcalendar --enable-ldap \
            --enable-dillo --enable-fancy --enable-rssyl --enable-spamassassin \
            --enable-bogofilter --enable-notification --enable-pdf-viewer \
            --enable-spam-report --enable-address-keeper --enable-acpi-notifier \
            --enable-maildir --enable-newmail --enable-managesieve \
          || { echo "Configuration failed, check config.log"; cat config.log; exit 1; }
          grep "yes" config.log || echo "No features explicitly enabled"

      - name: Build Claws Mail
        run: |
          cd ~/claws-mail-build/claws-mail-4.3.0
          make -j$(nproc) || { echo "Build failed"; exit 1; }

      - name: Install Claws Mail to a staging directory
        run: |
          cd ~/claws-mail-build/claws-mail-4.3.0
          mkdir -p ~/claws-mail-install/usr
          make install DESTDIR=~/claws-mail-install || { echo "Installation failed"; exit 1; }

      - name: Bundle all shared library dependencies
        run: |
          cd ~/claws-mail-install
          mkdir -p usr/lib
          cp ~/claws-mail-build/claws-mail-4.3.0/src/claws-mail usr/bin/
          ldd usr/bin/claws-mail | grep -o '/[^ ]*\.so[^ ]*' | sort -u | while read lib; do
            cp -v "$lib" usr/lib/ || { echo "Warning: $lib not found, may need manual inclusion"; continue; }
          done
          cp -v /usr/lib/libicu*.so.74* usr/lib/ || true
          cp -v /usr/lib/x86_64-linux-gnu/libgnutls*.so* usr/lib/ || true
          for lib in /usr/lib/x86_64-linux-gnu/*.so*; do
            cp -v "$lib" usr/lib/ || true
          done
          strip usr/bin/claws-mail usr/lib/*.so* 2>/dev/null || true

      - name: Create tarball with binary and libraries
        run: |
          cd ~/claws-mail-install
          tar -czf ~/claws-mail-4.3.0-void-bundled.tar.gz .

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: claws-mail-void-bundled
          path: ~/claws-mail-4.3.0-void-bundled.tar.gz

      - name: Display SHA256 checksum
        run: |
          sha256sum ~/claws-mail-4.3.0-void-bundled.tar.gz
