name: Build Claws Mail AppImage

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends \
            build-essential git wget curl autoconf automake libtool pkg-config \
            libglib2.0-dev libgtk-3-dev libnotify-dev libstartup-notification0-dev \
            libcompfaceg1-dev fuse3 libfuse3-dev xterm appstream musl-tools

      - name: Build Nettle
        run: |
          wget https://ftp.gnu.org/gnu/nettle/nettle-3.7.3.tar.gz
          tar xf nettle-3.7.3.tar.gz
          cd nettle-3.7.3
          CC=musl-gcc ./configure --prefix=/usr/local --enable-mini-gmp --enable-shared
          make -j$(nproc)
          sudo make install

      - name: Build GnuTLS
        run: |
          wget https://www.gnupg.org/ftp/gcrypt/gnutls/v3.7/gnutls-3.7.8.tar.xz
          tar xf gnutls-3.7.8.tar.xz
          cd gnutls-3.7.8
          export NETTLE_CFLAGS="-I/usr/local/include"
          export NETTLE_LIBS="-L/usr/local/lib -lnettle -lhogweed"
          export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig"
          CC=musl-gcc ./configure --prefix=/usr/local --with-included-libtasn1 --with-included-unistring --with-nettle-mini --without-p11-kit --disable-doc
          make -j$(nproc)
          sudo make install

      - name: Build libetpan
        run: |
          git clone https://github.com/dinhvh/libetpan.git
          cd libetpan
          ./autogen.sh
          CC=musl-gcc ./configure --prefix=/usr/local
          make -j$(nproc)
          sudo make install

      - name: Download Claws Mail 4.2.0
        run: |
          wget https://www.claws-mail.org/releases/claws-mail-4.2.0.tar.xz
          tar xf claws-mail-4.2.0.tar.xz

      - name: Build Claws Mail with debug
        run: |
          cd claws-mail-4.2.0
          ./configure --prefix=/tmp/appdir/usr
          make -j$(nproc)
          make install

      - name: Create AppImage structure
        run: |
          mkdir -p /tmp/appdir/usr/lib /tmp/appdir/usr/bin
          cp claws-mail-4.2.0/src/claws-mail /tmp/appdir/usr/bin/
          for lib in libgtk-3.so.0 libglib-2.0.so.0 libgobject-2.0.so.0 libnotify.so.4 \
                     libetpan.so.20 libgnutls.so.30 libcompface.so.1 \
                     libstartup-notification-1.so.0 ld-linux-x86-64.so.2 libc.so.6; do
            cp -v $(ldconfig -p | grep $lib | head -n1 | awk '{print $4}') /tmp/appdir/usr/lib/ || echo "$lib not found"
          done

      - name: Create AppRun
        run: |
          cat << 'EOF' > /tmp/appdir/AppRun
          #!/bin/bash
          export LD_LIBRARY_PATH="$(dirname "$0")/usr/lib:$LD_LIBRARY_PATH"
          export GNUTLS_DEBUG_LEVEL=9
          export GNUTLS_PRIORITY="NORMAL"
          LOGFILE="$HOME/claws-mail-appimage-run.log"
          echo "Launching Claws Mail with GnuTLS debugging" > "$LOGFILE"
          exec "$(dirname "$0")/usr/bin/claws-mail" "$@" >> "$LOGFILE" 2>&1
          EOF
          chmod +x /tmp/appdir/AppRun

      - name: Create .desktop and icon
        run: |
          echo '[Desktop Entry]
          Name=Claws Mail
          Exec=claws-mail
          Type=Application
          Icon=claws-mail
          Categories=Network;Email;' > /tmp/appdir/claws-mail.desktop

          mkdir -p /tmp/appdir/usr/share/icons/hicolor/48x48/apps
          wget -O /tmp/appdir/usr/share/icons/hicolor/48x48/apps/claws-mail.png https://www.claws-mail.org/images/claws-mail_icon_48.png

      - name: Package AppImage
        run: |
          wget -O linuxdeploy https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          chmod +x linuxdeploy
          ./linuxdeploy --appdir /tmp/appdir -d /tmp/appdir/claws-mail.desktop -i /tmp/appdir/usr/share/icons/hicolor/48x48/apps/claws-mail.png --output appimage

      - name: Upload AppImage
        uses: actions/upload-artifact@v4
        with:
          name: ClawsMail-AppImage
          path: ./*.AppImage
