name: Build Claws Mail Static Binary for Void

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: alpine:edge

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build tools and dependencies
        run: |
          apk update
          apk add --no-cache \
            bash build-base git curl wget pkgconf \
            musl-dev gtk+3.0-dev fuse \
            libetpan-dev gnutls-dev gpgme-dev enchant2-dev \
            poppler-dev libcanberra-dev libnotify-dev perl-dev \
            python3-dev libical-dev libarchive-dev openldap-dev \
            db-dev libx11-dev libsm-dev libsoup-dev \
            gumbo-parser-dev libsecret-dev json-glib-dev \
            ghostscript spamassassin appstream-glib webkit2gtk-4.1-dev \
            linux-headers glib-dev \
            gnutls-static zlib-static bzip2-static expat-static

      - name: Download Claws Mail source
        run: |
          mkdir -p ~/claws-mail-build
          cd ~/claws-mail-build
          wget "https://www.claws-mail.org/download.php?file=releases/claws-mail-4.3.0.tar.xz" -O claws-mail-4.3.0.tar.xz
          tar -xf claws-mail-4.3.0.tar.xz

      - name: Configure Claws Mail with static linking
        run: |
          cd ~/claws-mail-build/claws-mail-4.3.0
          LDFLAGS="-static" ./configure \
            --prefix=/usr \
            --enable-gtk3 --enable-libetpan --enable-gnutls --enable-pgp-core \
            --enable-pgp-inline --enable-pgp-mime --enable-enchant --enable-poppler \
            --enable-canberra --enable-notify --enable-perl --enable-python \
            --enable-vcalendar --enable-ldap \
            --enable-dillo --enable-fancy --enable-rssyl --enable-spamassassin \
            --enable-bogofilter --enable-notification --enable-pdf-viewer \
            --enable-spam-report --enable-address-keeper --enable-acpi-notifier \
            --enable-maildir --enable-newmail --enable-managesieve || \
            echo "Some plugins may be disabled; static linking may not fully succeed."

      - name: Build Claws Mail
        run: |
          cd ~/claws-mail-build/claws-mail-4.3.0
          make -j$(nproc)

      - name: Install Claws Mail to a staging directory
        run: |
          cd ~/claws-mail-build/claws-mail-4.3.0
          mkdir -p ~/claws-mail-install/usr/bin ~/claws-mail-install/usr/lib
          cp src/claws-mail ~/claws-mail-install/usr/bin/
          # Bundle shared libraries if static linking isn't complete
          ldd src/claws-mail | grep -o '/[^ ]*' | xargs -I {} cp -v {} ~/claws-mail-install/usr/lib/

      - name: Create tarball with binary and libraries
        run: |
          cd ~/claws-mail-install
          tar -czf ~/claws-mail-4.3.0-void-static.tar.gz .

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: claws-mail-void-static
          path: ~/claws-mail-4.3.0-void-static.tar.gz

      - name: Display SHA256 checksum
        run: |
          sha256sum ~/claws-mail-4.3.0-void-static.tar.gz
