name: Build Claws Mail AppImage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository (if you store this script or related files there)
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up environment and install dependencies
      - name: Install build tools and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential git curl wget pkg-config libgtk-3-dev libfuse2 \
            libetpan-dev libgnutls28-dev libgpgme-dev libenchant-2-dev \
            libpoppler-glib-dev libcanberra-dev libnotify-dev libperl-dev \
            python3-dev libytnef0-dev libical-dev libarchive-dev libldap2-dev \
            libcompfaceg1-dev libdb-dev libstartup-notification0-dev libx11-dev \
            libsm-dev libsoup2.4-dev libgumbo-dev libsecret-1-dev libjson-glib-dev \
            ghostscript spamassassin appstream || echo "Some optional deps failed."
          # Try WebKitGTK 4.0 or 4.1
          sudo apt-get install -y libwebkit2gtk-4.0-dev || \
          sudo apt-get install -y libwebkit2gtk-4.1-dev || \
          echo "WebKitGTK skipped; Fancy plugin may not work."

      # Set up working directory
      - name: Set up working directory
        run: |
          mkdir -p ~/claws-mail-appimage-build
          mkdir -p ~/claws-mail-appimage-build/install
          mkdir -p ~/claws-mail-appimage-build/ClawsMail.AppDir
          cd ~/claws-mail-appimage-build

      # Download and extract Claws Mail source
      - name: Download Claws Mail source
        run: |
          wget "https://www.claws-mail.org/download.php?file=releases/claws-mail-4.3.0.tar.xz" -O claws-mail-4.3.0.tar.xz
          tar -xf claws-mail-4.3.0.tar.xz
          cd claws-mail-4.3.0

      # Configure Claws Mail with all plugins
      - name: Configure Claws Mail
        run: |
          ./configure \
            --prefix="$HOME/claws-mail-appimage-build/install" \
            --enable-gtk3 --enable-libetpan --enable-gnutls --enable-pgp-core \
            --enable-pgp-inline --enable-pgp-mime --enable-enchant --enable-poppler \
            --enable-canberra --enable-notify --enable-perl --enable-python \
            --enable-tnef --enable-vcalendar --enable-ldap --enable-compface \
            --enable-dillo --enable-fancy --enable-rssyl --enable-spamassassin \
            --enable-bogofilter --enable-notification --enable-pdf-viewer \
            --enable-spam-report --enable-address-keeper --enable-acpi-notifier \
            --enable-maildir --enable-newmail --enable-managesieve || \
            echo "Some plugins may be disabled."

      # Build and install Claws Mail
      - name: Build and install Claws Mail
        run: |
          make -j$(nproc)
          make install

      # Set up AppImage directory structure
      - name: Prepare AppImage structure
        run: |
          cd ~/claws-mail-appimage-build/ClawsMail.AppDir
          mkdir -p usr/bin usr/lib usr/share/applications usr/share/icons/hicolor/48x48/apps usr/share/perl
          cp ~/claws-mail-appimage-build/install/bin/claws-mail usr/bin/
          if [ -f "~/claws-mail-appimage-build/install/share/applications/claws-mail.desktop" ]; then
            cp ~/claws-mail-appimage-build/install/share/applications/claws-mail.desktop .
            sed -i 's/Exec=claws-mail %u/Exec=AppRun/' claws-mail.desktop
            cp claws-mail.desktop usr/share/applications/
          else
            echo "[Desktop Entry]" > claws-mail.desktop
            echo "Name=Claws Mail" >> claws-mail.desktop
            echo "Exec=AppRun" >> claws-mail.desktop
            echo "Type=Application" >> claws-mail.desktop
            echo "Icon=claws-mail" >> claws-mail.desktop
            echo "Categories=Network;Email;" >> claws-mail.desktop
            echo "Terminal=false" >> claws-mail.desktop
            cp claws-mail.desktop usr/share/applications/
          fi
          chmod 644 claws-mail.desktop usr/share/applications/claws-mail.desktop
          if [ -f "~/claws-mail-appimage-build/install/share/icons/hicolor/48x48/apps/claws-mail.png" ]; then
            cp ~/claws-mail-appimage-build/install/share/icons/hicolor/48x48/apps/claws-mail.png claws-mail.png
            cp ~/claws-mail-appimage-build/install/share/icons/hicolor/48x48/apps/claws-mail.png usr/share/icons/hicolor/48x48/apps/
          else
            wget -O claws-mail.png "https://www.claws-mail.org/images/claws-mail_icon_48.png"
            cp claws-mail.png usr/share/icons/hicolor/48x48/apps/
          fi
          chmod 644 claws-mail.png usr/share/icons/hicolor/48x48/apps/claws-mail.png

      # Create AppRun with debug logging
      - name: Create AppRun with debug logging
        run: |
          cd ~/claws-mail-appimage-build/ClawsMail.AppDir
          cat <<EOF > AppRun
          #!/bin/bash
          HERE="\$(dirname "\$(readlink -f "\${0}")")"
          LOG_FILE="\$HOME/.claws-mail-appimage.log"
          echo "[$(date)] AppImage started" > "\$LOG_FILE"
          echo "Environment: \$PATH" >> "\$LOG_FILE"
          echo "LD_LIBRARY_PATH: \$LD_LIBRARY_PATH" >> "\$LOG_FILE"
          echo "Running claws-mail from: \$HERE/usr/bin/claws-mail" >> "\$LOG_FILE"
          "\$HERE/usr/bin/claws-mail" "\$@" 2>> "\$LOG_FILE"
          EXIT_CODE=\$?
          echo "[$(date)] AppImage exited with code \$EXIT_CODE" >> "\$LOG_FILE"
          exit \$EXIT_CODE
          EOF
          chmod +x AppRun

      # Bundle external tools
      - name: Bundle external tools
        run: |
          cd ~/claws-mail-appimage-build/ClawsMail.AppDir
          cp /usr/bin/gs usr/bin/
          cp /usr/bin/spamassassin usr/bin/
          cp /usr/bin/perl usr/bin/
          if [ -d "/usr/lib/x86_64-linux-gnu/perl" ]; then
            cp -r /usr/lib/x86_64-linux-gnu/perl usr/lib/
          elif [ -d "/usr/lib/x86_64-linux-gnu/perl5" ]; then
            cp -r /usr/lib/x86_64-linux-gnu/perl5 usr/lib/
          else
            echo "Warning: Perl libraries not found; SpamAssassin may not work."
          fi
          if [ -d "/usr/share/perl" ]; then
            cp -r /usr/share/perl/* usr/share/perl/
          fi

      # Download linuxdeploy and appimagetool
      - name: Download build tools
        run: |
          cd ~/claws-mail-appimage-build
          wget "https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage" -O linuxdeploy.AppImage
          wget "https://github.com/AppImage/AppImageKit/releases/download/13/appimagetool-x86_64.AppImage" -O appimagetool.AppImage
          chmod +x linuxdeploy.AppImage appimagetool.AppImage

      # Bundle dependencies and create AppImage
      - name: Bundle dependencies and create AppImage
        run: |
          cd ~/claws-mail-appimage-build
          ./linuxdeploy.AppImage --appdir ClawsMail.AppDir \
            --executable=ClawsMail.AppDir/usr/bin/claws-mail \
            --executable=ClawsMail.AppDir/usr/bin/gs \
            --executable=ClawsMail.AppDir/usr/bin/perl \
            --desktop-file=ClawsMail.AppDir/claws-mail.desktop \
            --icon-file=ClawsMail.AppDir/claws-mail.png
          ./appimagetool.AppImage ClawsMail.AppDir claws-mail-4.3.0.AppImage

      # Upload AppImage as artifact
      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v4
        with:
          name: claws-mail-appimage
          path: ~/claws-mail-appimage-build/claws-mail-4.3.0.AppImage

      # Display SHA256 checksum
      - name: Display SHA256 checksum
        run: |
          sha256sum ~/claws-mail-appimage-build/claws-mail-4.3.0.AppImage
